# Generated by Django 3.0.8 on 2021-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(default='Bucharest', max_length=100),
            preserve_default=False,
        ),
    ]
