# Generated by Django 3.0.8 on 2021-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_clinic_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dentist',
            name='speciality',
            field=models.ManyToManyField(to='database.Speciality'),
        ),
    ]
