# Generated by Django 3.0.8 on 2021-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210618_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='first_name',
            field=models.CharField(default='Dentistu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentist',
            name='last_name',
            field=models.CharField(default='Doctoru', max_length=100),
            preserve_default=False,
        ),
    ]
