# Generated by Django 3.0.8 on 2021-06-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210618_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='Dentistu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='Dentist', max_length=100),
            preserve_default=False,
        ),
    ]
