# Generated by Django 3.0.8 on 2021-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210618_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='firstname',
            field=models.CharField(default='Dentistoo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentist',
            name='lastname',
            field=models.CharField(default='dentist', max_length=100),
            preserve_default=False,
        ),
    ]
