# Generated by Django 3.0.8 on 2021-06-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210618_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.ManyToManyField(to='database.Speciality'),
        ),
    ]
