# Generated by Django 3.0.8 on 2021-06-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_user_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='speciality',
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(default='3 4', max_length=10),
            preserve_default=False,
        ),
    ]
