# Generated by Django 3.0.8 on 2021-06-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20210618_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='Clinica denta', max_length=100),
            preserve_default=False,
        ),
    ]
