# Generated by Django 3.0.8 on 2021-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
