# Generated by Django 3.0.8 on 2021-06-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_patient_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(upload_to='../Dentapp-frontend/src/assets/img/patients/avatars/'),
        ),
    ]
