# Generated by Django 3.0.8 on 2021-06-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20210621_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='avatar',
            field=models.ImageField(default='eee', upload_to='../Dentapp-frontend/src/assets/img/dentists/avatars/'),
            preserve_default=False,
        ),
    ]
