# Generated by Django 3.0.8 on 2021-06-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_dentist_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='avatar',
            field=models.ImageField(default='../Dentapp-frontend/src/assets/img/dentists/avatars/avatar.jpeg', upload_to='../Dentapp-frontend/src/assets/img/dentists/avatars/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(default='../Dentapp-frontend/src/assets/img/dentists/avatars/avatar.jpeg', upload_to='../Dentapp-frontend/src/assets/img/patients/avatars/'),
        ),
    ]
