# Generated by Django 3.0.8 on 2021-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20210621_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='uic',
            field=models.CharField(default='23314451243321', max_length=20),
            preserve_default=False,
        ),
    ]
