# Generated by Django 3.0.8 on 2021-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_clinic_uic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uic',
            field=models.CharField(default='255423534545', max_length=20),
            preserve_default=False,
        ),
    ]
