# Generated by Django 3.0.8 on 2021-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_user_uic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinicName',
            field=models.CharField(default='S.C. BLEAHU S.R.L.', max_length=40),
            preserve_default=False,
        ),
    ]
