# Generated by Django 3.0.8 on 2021-06-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_user_clinicname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clinicName',
        ),
    ]
